<div id="header">

  <div id="menu">
    <?php
       if(isset($_layoutParams['menu'])){

          for ($i=0; $i<count($_layoutParams['menu']);$i++) {

             ($_layoutParams['menu'][$i]['id'] == $item)? $estilo = 'botonActivado'
                                                        : $estilo = 'botonMenu';           
    ?>
             <div class="<?php echo $estilo; ?>">
                 <a href="<?php echo $_layoutParams['menu'][$i]['enlace']; ?>">
                  <?php echo $_layoutParams['menu'][$i]['titulo']; ?>
                 </a>
             </div>
     <?php
          }
       }
     ?>
  </div>

     <img src=
        "<?php echo $_layoutParams['ruta_img'];?>dawymLogo.png"
     alt="Desarrollo de Aplicaciones" title="Desarrollo de Aplicaciones">

    <h1><?php echo NOMBRE_APP; ?></h1>
   
    <h4>
    <?php if(isset($_GET['materia']) && isset($this->materia[0]["titulo"])) {
              echo $this->materia[0]["titulo"];
          } else {
              echo "Listado contenidos de materias";
          }  


    ?>	
    </h4>

  <?php $num_ufos = count($this->materia); ?>
  
  <div id="materias"> 
     <table>
      <?php for($i=0;$i<$num_ufos;$i++){ ?>
        <tr>
          <th> 
          <?php
               //solo nos muestra el nombre de la materia una vez
              //mientras las ufos sean de esa misma materia
            if (!isset($_GET['materia'])) {
                if (!isset($condicion) || $condicion != $this->materia[$i]['titulo']) {
                      echo '<br>'.$this->materia[$i]['titulo'].'<br>';
                    }
               
               $condicion = $this->materia[$i]['titulo'];
              }
           
               echo '<a href="'.BASE_URL.'ufo/index.phtml?ufo='.$this->materia[$i]['id'].'&materia='.$this->materia[$i]['id_materia'].'">'.$this->materia[$i]['nombre'].'</a>';
             ?>
            </th>
         </tr>
         
      <?php } ?>
     </table>
  </div>

</div>
<div id="footerMini">

</div>
</body>
</html>
<!--     

  




 