<div id="header">

<div id="menu">
	<?php
       if(isset($_layoutParams['menu'])){

       	  for ($i=0; $i<count($_layoutParams['menu']);$i++) {

       	  	 ($_layoutParams['menu'][$i]['id'] == $item)? $estilo = 'botonActivado'
       	  	                                            : $estilo = 'botonMenu';
       	  	 
            ?>
             <div class="<?php echo $estilo; ?>">
                 <a href="<?php echo $_layoutParams['menu'][$i]['enlace']; ?>">
                 	<?php echo $_layoutParams['menu'][$i]['titulo']; ?>
                 </a>
             </div>
            <?php
       	  }
       }
	?>
</div>

     <img src=
        "<?php echo $_layoutParams['ruta_img'];?>dawymLogo.png"
     alt="Desarrollo de Aplicaciones" title="Desarrollo de Aplicaciones">

    <h1><?php echo $this->titulo;?></h1>
     
     <form name="materiaform" action="<?php echo BASE_URL;?>admin/newmateria">
      <br>
      <hr>
     	<p>
     		MATERIA : <input type="text" name="nombre"/>
     	</p>
      <br>
     	<input type="submit" name="confirmamateria" value="GUARDAR NUEVA MATERIA">
      <hr>
     </form>
    
</div>   