<div id="headerlong">

<div id="menu">
	<?php
       if(isset($_layoutParams['menu'])){

       	  for ($i=0; $i<count($_layoutParams['menu']);$i++) {

       	  	 ($_layoutParams['menu'][$i]['id'] == $item)? $estilo = 'botonActivado'
       	  	                                            : $estilo = 'botonMenu';
       	  	 
   ?>
             <div class="<?php echo $estilo; ?>">
                 <a href="<?php echo $_layoutParams['menu'][$i]['enlace']; ?>">
                 	<?php echo $_layoutParams['menu'][$i]['titulo']; ?>
                 </a>
             </div>
    <?php
       	  }
       }
	   ?>
</div>

     <img src=
        "<?php echo $_layoutParams['ruta_img'];?>dawymLogo.png"
     alt="Desarrollo de Aplicaciones" title="Desarrollo de Aplicaciones">

    <h1><?php echo $this->titulo;?></h1>

    <br><hr><hr><br><hr><br>

  <div class="formulario">

    <form name="materiaform" method="POST" action="<?php echo BASE_URL;?>admin/newmateria">

       <input type="hidden" name="guardar" value="1">
     	<p>
     		MATERIA : <input type="text" name="nombre"/>
     	</p>
      <br>
     	<input type="submit" class="botonform" name="confirmamateria" value="GUARDAR NUEVA MATERIA" />

    </form>
     <br>
      <hr>
      <?php
        if (isset($this->materianew) && !empty($this->materianew)) {

            echo "<h3>CONFIRMAS QUE QUIERES CREAR ";
            echo $this->materianew;
            
       ?>
             COMO NUEVA MATERIA</h3><br>

            <div class="botonAdmin">
                <a href=""> CONFIRMAR</a>
           </div>

           <div class="botonAdmin">
                <a href="<?php echo BASE_URL;?>admin"> CANCELAR</a>
           </div>
      <?php     
        }
       ?>
  </div>
    
</div>   