<div id="header">

  <div id="menu">
  <?php
       if(isset($_layoutParams['menu'])){

          for ($i=0; $i<count($_layoutParams['menu']);$i++) {

             ($_layoutParams['menu'][$i]['id'] == $item)? $estilo = 'botonActivado'
                                                        : $estilo = 'botonMenu';
             
   ?>
             <div class="<?php echo $estilo; ?>">
                 <a href="<?php echo $_layoutParams['menu'][$i]['enlace']; ?>">
                  <?php echo $_layoutParams['menu'][$i]['titulo']; ?>
                 </a>
             </div>
   <?php
          }
       }
    ?>
  </div>

     <img src=
        "<?php echo $_layoutParams['ruta_img'];?>dawymLogo.png"
     alt="Desarrollo de Aplicaciones" title="Desarrollo de Aplicaciones">

    <h1><?php echo NOMBRE_APP; ?></h1>

      <h4>Listado de conceptos</h4>


  <div id="conceptos"> 
     <br>

    <?php

       $num_conceptos = count($this->concepto);
       for($n=0;$n<$num_conceptos;$n++){ ?>
        
            <?php
               echo  '<p>'.$this->concepto[$n]['palabra'].'</p>';
            ?>
           
         
     <?php } ?>
    
   </div>
</div>



<div id="footerMini">

</div>
</body>
</html>
<!--     

 