<div id="header">

     <img src=
        "<?php echo $_layoutParams['ruta_img'];?>dawymLogo.png"
     alt="Desarrollo de Aplicaciones" title="Desarrollo de Aplicaciones">

    <h1><?php echo NOMBRE_APP; ?></h1>
    <h4><?php echo SLOGAN_APP; ?></h4>

    <?php $num_materias = count($this->materias); ?>
  <div id="materias"> 
    <table>
     <?php for($n=0;$n<$num_materias;$n++){ ?>
        <tr>
            <th><?php echo $this->materias[$n]['id']; ?></th>
            <th>
            <?php
               echo  '<a href="materia/index.phtml?materia='.$this->materias[$n]['id'].'">'. $this->materias[$n]['nombre'].'</a>';
             ?>
            </th>
        </tr>
         
     <?php } ?>
    </table>
  </div>    


</div>

<div id="menu">
	<?php
       if(isset($_layoutParams['menu'])){

       	  for ($i=0; $i<count($_layoutParams['menu']);$i++) {

       	  	 ($_layoutParams['menu'][$i]['id'] == $item)? $estilo = 'botonActivado'
       	  	                                            : $estilo = 'botonMenu';
       	  	 
            ?>
             <div class="<?php echo $estilo; ?>">
                 <a href="<?php echo $_layoutParams['menu'][$i]['enlace']; ?>">
                 	<?php echo $_layoutParams['menu'][$i]['titulo']; ?>
                 </a>
             </div>
            <?php
       	  }
       }
	?>
</div>

